### ISSUE TITLE
V2: Better "Last Touch" functionality

### ISSUE THREAD

**Issue by shirey** [x-atlas-consortia/data-ingest-board#105]
- Change the functionality of the returned value for `last_touch` from `/datasets/data-status` such that it returns the value of `Dataset.published_timestamp` for `last_touch`, otherwise it returns the `Dataset.last_modified_timestamp` as it is now.

- If easy (if not, no worries) add a help pop-up message in the column header for Last Touch that says "If the dataset is published Last Touch returns the date/time that the dataset was published, otherwise it returns the date/time that the dataset record was last updated.  NOTE: This does not include updates to data via Globus (or otherwise), only updates to metadata stored in the HuBMAP provenance database."

**Comment by libpitt** [comment]
![Screen Shot 2023-11-14 at 2 49 37 PM](https://github.com/hubmapconsortium/data-ingest-board/assets/115558393/c9542009-05b2-4409-9370-1dccec7b6680)

**Comment by yuanzhou** [comment]
Removed @DerekFurstPitt from this task since @libpitt already addressed the issue in both data-ingest-board UI and backend ingest-api for both HuBMAP and SenNet.
