### ISSUE TITLE
Remove usage of Dataset `data_types`

### ISSUE THREAD

**Issue by yuanzhou** [x-atlas-consortia/data-ingest-board#133]
Remove the unused `uniqueDataType` constant:

https://github.com/x-atlas-consortia/data-ingest-board/blob/819bcc35b881ec9748acb31676636e9dac3b1ed3/src/components/DataTable/DatasetTable.jsx#L40-L50

**Comment by shirey** [comment]
@maxsibilla , If @libpitt is working in the data ingest board, I'll ask her to take care of this.  I think it is just dead code that needs to be removed.
