### ISSUE TITLE
links don't preserve the search

### ISSUE THREAD

**Issue by bherr2** [x-atlas-consortia/data-ingest-board#136]
Going here: https://ingest.board.hubmapconsortium.org/?group_name=stanford+tmc&has_rui_info=false shows 4 selected as the header (which is right, but shows way more than 4). Seems part of the url parameters are being missed when loading?

![image](https://github.com/x-atlas-consortia/data-ingest-board/assets/34098595/05448546-3804-453d-a91c-0fcfa536b0da)

**Comment by maxsibilla** [comment]
@bherr2 This has been fixed
