### ISSUE TITLE
Ingest/Publication Dashboad mobile ready

### ISSUE THREAD

**Issue by shirey** [x-atlas-consortia/data-ingest-board#17]

**Comment by DerekFurstPitt** [comment]
Reposition Dataset/Upload toggle button and clear button on narrow screens to stack vertically on top of each other

**Comment by libpitt** [comment]
@shirey and @DerekFurstPitt Can you two detail if anything else needs to be done. This was made mobile ready a while back and this card maybe already resolved. (We already have the buttons stacked vertically.)  

![Screen Shot 2024-01-11 at 9 43 49 AM](https://github.com/x-atlas-consortia/data-ingest-board/assets/115558393/292cb295-dff2-4191-a357-1cd52eb84098)
