### ISSUE TITLE
Make Incomplete Status Yellow on Data Ingest Board

### ISSUE THREAD

**Issue by bhonick** [x-atlas-consortia/data-ingest-board#182]
@shirey @DerekFurstPitt Please change the color of the Incomplete status on the Data Ingest Board from gray to yellow to match the color used on the Ingest UI:

![image](https://github.com/x-atlas-consortia/data-ingest-board/assets/71984404/a6948831-5b98-4ae7-b05b-e56d42b2d9a4)
![image](https://github.com/x-atlas-consortia/data-ingest-board/assets/71984404/3796d771-273d-4383-8caa-6c7c602edf7d)

**Comment by maxsibilla** [comment]
This is something that is defined in the .env file. See SenNet for an example
https://github.com/x-atlas-consortia/data-ingest-board/blob/e1bce9be5ec63222a3a08c7c16fd475aef3bcd6f/src/example.sennet.env#L21

**Comment by yuanzhou** [comment]
@BirdMachine what's the Hex color code of the yellow badge you used for Ingest Portal Incomplete status? @maxsibilla and I can configure with that color when we deploy the Data Ingest Board next time.

**Comment by DerekFurstPitt** [comment]
@yuanzhou 

She shared the css with me. For incomplete she uses 

.badge-incomplete { background-color: rgb(255, 193, 7); color: rgb(33, 37, 41); }

**Comment by yuanzhou** [comment]
Thanks @DerekFurstPitt. @libpitt can we use RGB color in the config or it has to be Hex code?

**Comment by libpitt** [comment]
@yuanzhou Use the example.env config for HM on the board. 
https://github.com/x-atlas-consortia/data-ingest-board/blob/e1bce9be5ec63222a3a08c7c16fd475aef3bcd6f/src/example.env#L22

It's up to date with status colors. You should have an entry for `incomplete` as `#ffc107:#212529` just as @maxsibilla noted above.

**Comment by yuanzhou** [comment]
Thanks @libpitt.

**Comment by bhonick** [comment]
Thanks!
