### ISSUE TITLE
V2-Derived Datasets Support.

### ISSUE THREAD

**Issue by DerekFurstPitt** [x-atlas-consortia/data-ingest-board#22]
In drop down, add link to display derived datasets. Use modal to display the hubmap ID which is linked to both the data portal and the ingest portal, status, and datatype.

**Comment by shirey** [comment]
@DerekFurstPitt @yuanzhou -- I think we need a separate column for (Derived Datasets)- which either lists the ID of the dataset if there is a single derived dataset or a count of how many derived datasets there are, which when clicked pops up the full list which contains clickable IDs.

**Comment by maxsibilla** [comment]
Potentially related card: https://github.com/x-atlas-consortia/data-ingest-board/issues/10

**Comment by maxsibilla** [comment]
After talking with Brendan we will need to add a new column for derived datasets. In the cell for the primary dataset we simply need to list whether or not it contains any derived datasets. If you click on the cell it should launch a modal that displays a table of all derived datasets. The headers should be `SenNet/HuBMAP ID` (should be clickable and direct to the page), `Status`, and `Creation Date`.

**Comment by libpitt** [comment]
<img width="906" alt="Screen Shot 2024-02-09 at 2 10 15 PM" src="https://github.com/x-atlas-consortia/data-ingest-board/assets/115558393/5cc478a3-c8e9-42bc-8d91-e3b32aafe4d9">
