### ISSUE TITLE
Create new visual summary section

### ISSUE THREAD

**Issue by maxsibilla** [x-atlas-consortia/data-ingest-board#228]
This new section will go between the search bar and the results table:
<img width="1311" alt="image" src="https://github.com/user-attachments/assets/325f94b6-8b4a-462a-b0a2-be54807c3aeb">

We will want to generate D3 graphs based on the results returned by selected filters. For example

- Pie chart displaying the the statuses of the results
- Pie or bar chart for data provider groups
- Bar chart for the dataset type
- etc...
If a filter is selected (e.g. `status`) then we do not need to show any graph so it should be hidden. We should also allow each graph to be expanded to view it full screen.

**Comment by libpitt** [comment]
Branch mock up:
https://github.com/x-atlas-consortia/data-ingest-board/tree/libpitt/228-visualizations

Powerpoint doc:
https://docs.google.com/presentation/d/1dzI2AaKmRaqFvZkG4FBmrlolwWpx9v-B2uTQnuCBOMk/edit#slide=id.p

**Comment by yuanzhou** [comment]
@libpitt can you make the slides read-only for viewers so I don't have to request access?

**Comment by maxsibilla** [comment]
We will be proceeding with proposal 2 from the wireframe. Additional requests:

- [ ] In both the carousel and full screen modal view, when hovering over any section of the graph we want to display the category and count.
  - Example: If the user hovers over a bar chart displaying `Data Provider Group` it should  display something like `TMC - Yale University - Fan`: 150

- [ ] In the full screen modal view if a user clicks on a specific bar, this should trigger a filter selection.
  - Example:  If the clicks on the bar for `TMC - Yale University - Fan` then the `data_provider_group` column should be filtered by this group and the entire site and all graphs should be updated to reflect this
  - Alternatively we can also add a filter button in the full screen modal view to accomplish this
